name: ci

on:
  push:
    branches:
      - 'master'
    paths:
      - Dockerfile

jobs:
  push_17:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_ver: [latest, 3.16, 3.15]
        jre_ver: [17-jre-headless]
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get-id
        run: |
          id=$(echo ${{ matrix.jre_ver }} | cut -d- -f1)
          echo "::set-output name=id::$id"
      - run: echo "${{steps.get-id.outputs.id}}"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: | 
            ALPINE_VERSION=${{ matrix.alpine_ver }}
            JRE_VERSION=${{ matrix.jre_ver }}
          push: true
          tags: sapvs/openjre-alpine:${{ steps.get-id.outputs.id }}-${{ matrix.alpine_ver }}
  push_11_8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_ver: [latest, 3.16, 3.15, 3.14]
        jre_ver: [8-jre-base, 11-jre-headless]
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get-id
        run: |
          id=$(echo ${{ matrix.jre_ver }} | cut -d- -f1)
          echo "::set-output name=id::$id"
      - run: echo "${{ steps.get-id.outputs.id }}"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: | 
            ALPINE_VERSION=${{ matrix.alpine_ver }}
            JRE_VERSION=${{ matrix.jre_ver }}
          push: true
          tags: sapvs/openjre-alpine:${{ steps.get-id.outputs.id }}-${{ matrix.alpine_ver }}
